name: Update Index
env:
  TZ: Asia/Shanghai

on:
  push:
  pull_request:
    types: [opened, closed]
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整的git历史记录用于时间戳
        ref: ${{ github.event.pull_request.base.ref }}  # PR合并时检出目标分支
    
    - name: Set up Dart
      uses: dart-lang/setup-dart@v1
    
    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Checkout PR
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh pr checkout ${{ github.event.pull_request.number }}
  
    - name: Run update script
      run: dart script/update_index.dart
    
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push
